services:
  - type: web
    name: employee-attendance
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: employee-attendance-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PIN
        value: "1234"

databases:
  - name: employee-attendance-db
    plan: free
